// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package ldapaggregator

import context "context"

import gorm1 "github.com/jinzhu/gorm"

import fmt "fmt"
import math "math"
import _ "github.com/envoyproxy/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type LdapAggregatorDefaultServer struct {
	DB *gorm1.DB
}

// List ...
func (m *LdapAggregatorDefaultServer) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	db := m.DB
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithBeforeList); ok {
		var err error
		if db, err = custom.BeforeList(ctx, db); err != nil {
			return err
		}
	}
	res, err := DefaultListLdapConfig(ctx, db)
	if err != nil {
		return err
	}
	out.Results = res

	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithAfterList); ok {
		var err error
		if err = custom.AfterList(ctx, out, db); err != nil {
			return err
		}
	}
	return nil
}

// LdapAggregatorLdapConfigWithBeforeList called before DefaultListLdapConfig in the default List handler
type LdapAggregatorLdapConfigWithBeforeList interface {
	BeforeList(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// LdapAggregatorLdapConfigWithAfterList called before DefaultListLdapConfig in the default List handler
type LdapAggregatorLdapConfigWithAfterList interface {
	AfterList(context.Context, *ListResponse, *gorm1.DB) error
}

// Create ...
func (m *LdapAggregatorDefaultServer) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	db := m.DB
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithBeforeCreate); ok {
		var err error
		if db, err = custom.BeforeCreate(ctx, db); err != nil {
			return err
		}
	}
	res, err := DefaultCreateLdapConfig(ctx, in.GetPayload(), db)
	if err != nil {
		return err
	}
	out.Result = res
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithAfterCreate); ok {
		var err error
		if err = custom.AfterCreate(ctx, out, db); err != nil {
			return err
		}
	}
	return nil
}

// LdapAggregatorLdapConfigWithBeforeCreate called before DefaultCreateLdapConfig in the default Create handler
type LdapAggregatorLdapConfigWithBeforeCreate interface {
	BeforeCreate(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// LdapAggregatorLdapConfigWithAfterCreate called before DefaultCreateLdapConfig in the default Create handler
type LdapAggregatorLdapConfigWithAfterCreate interface {
	AfterCreate(context.Context, *CreateResponse, *gorm1.DB) error
}

// Read ...
func (m *LdapAggregatorDefaultServer) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	db := m.DB
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithBeforeRead); ok {
		var err error
		if db, err = custom.BeforeRead(ctx, db); err != nil {
			return err
		}
	}
	res, err := DefaultReadLdapConfig(ctx, &LdapConfig{Id: in.GetId()}, db)
	if err != nil {
		return err
	}
	out.Result = res
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithAfterRead); ok {
		var err error
		if err = custom.AfterRead(ctx, out, db); err != nil {
			return err
		}
	}
	return nil
}

// LdapAggregatorLdapConfigWithBeforeRead called before DefaultReadLdapConfig in the default Read handler
type LdapAggregatorLdapConfigWithBeforeRead interface {
	BeforeRead(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// LdapAggregatorLdapConfigWithAfterRead called before DefaultReadLdapConfig in the default Read handler
type LdapAggregatorLdapConfigWithAfterRead interface {
	AfterRead(context.Context, *ReadResponse, *gorm1.DB) error
}

// Update ...
func (m *LdapAggregatorDefaultServer) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	var err error
	var res *LdapConfig
	db := m.DB
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithBeforeUpdate); ok {
		var err error
		if db, err = custom.BeforeUpdate(ctx, db); err != nil {
			return err
		}
	}
	res, err = DefaultStrictUpdateLdapConfig(ctx, in.GetPayload(), db)
	if err != nil {
		return err
	}
	out.Result = res
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithAfterUpdate); ok {
		var err error
		if err = custom.AfterUpdate(ctx, out, db); err != nil {
			return err
		}
	}
	return nil
}

// LdapAggregatorLdapConfigWithBeforeUpdate called before DefaultUpdateLdapConfig in the default Update handler
type LdapAggregatorLdapConfigWithBeforeUpdate interface {
	BeforeUpdate(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// LdapAggregatorLdapConfigWithAfterUpdate called before DefaultUpdateLdapConfig in the default Update handler
type LdapAggregatorLdapConfigWithAfterUpdate interface {
	AfterUpdate(context.Context, *UpdateResponse, *gorm1.DB) error
}

// Delete ...
func (m *LdapAggregatorDefaultServer) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	db := m.DB
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithBeforeDelete); ok {
		var err error
		if db, err = custom.BeforeDelete(ctx, db); err != nil {
			return err
		}
	}
	err := DefaultDeleteLdapConfig(ctx, &LdapConfig{Id: in.GetId()}, db)
	if err != nil {
		return err
	}
	if custom, ok := interface{}(in).(LdapAggregatorLdapConfigWithAfterDelete); ok {
		var err error
		if err = custom.AfterDelete(ctx, out, db); err != nil {
			return err
		}
	}
	return nil
}

// LdapAggregatorLdapConfigWithBeforeDelete called before DefaultDeleteLdapConfig in the default Delete handler
type LdapAggregatorLdapConfigWithBeforeDelete interface {
	BeforeDelete(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// LdapAggregatorLdapConfigWithAfterDelete called before DefaultDeleteLdapConfig in the default Delete handler
type LdapAggregatorLdapConfigWithAfterDelete interface {
	AfterDelete(context.Context, *DeleteResponse, *gorm1.DB) error
}
type LdapAggregatorDefaultGRPCServer struct {
	s *LdapAggregatorDefaultServer
}

func NewLdapAggregatorDefaultGRPCServer(db *gorm1.DB) *LdapAggregatorDefaultGRPCServer {
	return &LdapAggregatorDefaultGRPCServer{s: &LdapAggregatorDefaultServer{DB: db}}
}

// List ...
func (m *LdapAggregatorDefaultGRPCServer) List(ctx context.Context, in *ListRequest) (*ListResponse, error) {
	out := &ListResponse{}
	if err := m.s.List(ctx, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Create ...
func (m *LdapAggregatorDefaultGRPCServer) Create(ctx context.Context, in *CreateRequest) (*CreateResponse, error) {
	out := &CreateResponse{}
	if err := m.s.Create(ctx, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Read ...
func (m *LdapAggregatorDefaultGRPCServer) Read(ctx context.Context, in *ReadRequest) (*ReadResponse, error) {
	out := &ReadResponse{}
	if err := m.s.Read(ctx, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Update ...
func (m *LdapAggregatorDefaultGRPCServer) Update(ctx context.Context, in *UpdateRequest) (*UpdateResponse, error) {
	out := &UpdateResponse{}
	if err := m.s.Update(ctx, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Delete ...
func (m *LdapAggregatorDefaultGRPCServer) Delete(ctx context.Context, in *DeleteRequest) (*DeleteResponse, error) {
	out := &DeleteResponse{}
	if err := m.s.Delete(ctx, in, out); err != nil {
		return nil, err
	}
	return out, nil
}
