// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package ldapaggregator

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Results              []*LdapConfig `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResults() []*LdapConfig {
	if m != nil {
		return m.Results
	}
	return nil
}

type CreateRequest struct {
	Payload              *LdapConfig `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPayload() *LdapConfig {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateResponse struct {
	Result               *LdapConfig `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	AlreadyExists        bool        `protobuf:"varint,2,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() *LdapConfig {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateResponse) GetAlreadyExists() bool {
	if m != nil {
		return m.AlreadyExists
	}
	return false
}

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Result               *LdapConfig `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	NotFound             bool        `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetResult() *LdapConfig {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ReadResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type UpdateRequest struct {
	Payload              *LdapConfig `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetPayload() *LdapConfig {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateResponse struct {
	Result               *LdapConfig `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	NotFound             bool        `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() *LdapConfig {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UpdateResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	NotFound             bool     `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "ldap_aggregator.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ldap_aggregator.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "ldap_aggregator.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "ldap_aggregator.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "ldap_aggregator.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ldap_aggregator.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "ldap_aggregator.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "ldap_aggregator.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "ldap_aggregator.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "ldap_aggregator.DeleteResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0xa7, 0xb8, 0xe9, 0x24, 0x36, 0x91, 0x2f, 0xa4, 0x2e, 0xa5, 0x91, 0x25, 0xa4,
	0x5e, 0x12, 0x4b, 0xad, 0xb8, 0x70, 0x6b, 0x43, 0x91, 0x2a, 0xf5, 0x64, 0x89, 0x0b, 0x1c, 0xc2,
	0x26, 0x3b, 0x31, 0x2b, 0xb9, 0xbb, 0x66, 0x77, 0x53, 0xb5, 0xaf, 0xc0, 0x9d, 0x87, 0x69, 0x4e,
	0xbc, 0x0e, 0x6f, 0x81, 0x9c, 0x5d, 0x63, 0x9c, 0xba, 0x02, 0x09, 0xb8, 0x79, 0x76, 0xfe, 0xfd,
	0xf7, 0xd3, 0xcc, 0x2f, 0x83, 0xaf, 0x50, 0xde, 0xb0, 0x05, 0x4e, 0x0a, 0x29, 0xb4, 0x08, 0x9f,
	0xe6, 0x94, 0x14, 0x33, 0x92, 0x65, 0x12, 0x33, 0xa2, 0x85, 0x8c, 0x5e, 0x67, 0x4c, 0x7f, 0x5a,
	0xcd, 0x27, 0x0b, 0x71, 0x9d, 0x30, 0xbe, 0x14, 0xf3, 0x5c, 0xdc, 0x8a, 0x02, 0x79, 0xb2, 0xd1,
	0x2f, 0xc6, 0x19, 0xf2, 0x71, 0x26, 0xe4, 0x75, 0x22, 0x0a, 0xcd, 0x04, 0x57, 0x49, 0x59, 0x18,
	0xb3, 0xe8, 0xd9, 0x0d, 0xc9, 0x19, 0x25, 0x1a, 0x93, 0xea, 0xc3, 0x36, 0xfa, 0x0b, 0xc1, 0x97,
	0x2c, 0x33, 0x55, 0xec, 0x43, 0xef, 0x8a, 0x29, 0x9d, 0xe2, 0xe7, 0x15, 0x2a, 0x1d, 0x5f, 0x40,
	0xdf, 0x94, 0xaa, 0x10, 0x5c, 0x61, 0xf8, 0x0a, 0x76, 0x25, 0xaa, 0x55, 0xae, 0xd5, 0xd0, 0x19,
	0x75, 0x8e, 0x7b, 0x27, 0x07, 0x93, 0x2d, 0xc8, 0xc9, 0x15, 0x25, 0xc5, 0x74, 0x63, 0x99, 0x56,
	0xda, 0x38, 0x05, 0x7f, 0x2a, 0x91, 0x68, 0xb4, 0xbe, 0xe1, 0x19, 0xec, 0x16, 0xe4, 0x2e, 0x17,
	0x84, 0x0e, 0x9d, 0x91, 0xf3, 0x1b, 0x9f, 0x73, 0x58, 0x7f, 0xff, 0xd6, 0x79, 0xf2, 0xc5, 0x71,
	0x07, 0x4e, 0x5a, 0xdd, 0x8b, 0x73, 0x08, 0x2a, 0x4f, 0x0b, 0x77, 0x0a, 0x9e, 0x79, 0xf0, 0x0f,
	0x3c, 0x53, 0x2b, 0x0d, 0x5f, 0x42, 0x40, 0x72, 0x89, 0x84, 0xde, 0xcd, 0xf0, 0x96, 0x29, 0xad,
	0x86, 0xee, 0xc8, 0x39, 0xee, 0xa6, 0xbe, 0x3d, 0xbd, 0xd8, 0x1c, 0xc6, 0x87, 0xd0, 0x4b, 0x91,
	0xd0, 0x8a, 0x3f, 0x00, 0x97, 0x19, 0xf4, 0xbd, 0xd4, 0x65, 0x34, 0xfe, 0x08, 0x7d, 0xd3, 0xfe,
	0x1b, 0x94, 0x03, 0xd8, 0xe3, 0x42, 0xcf, 0x96, 0x62, 0xc5, 0xa9, 0xa5, 0xe8, 0x72, 0xa1, 0xdf,
	0x96, 0x75, 0x39, 0xc2, 0x77, 0x05, 0xfd, 0xb7, 0x23, 0x9c, 0x43, 0x50, 0x79, 0xfe, 0x37, 0xee,
	0x23, 0xf0, 0xdf, 0x60, 0x8e, 0x35, 0xf7, 0xf6, 0xe8, 0xc6, 0x10, 0x54, 0x02, 0x0b, 0xd1, 0xf0,
	0x73, 0x9a, 0x7e, 0x27, 0x5f, 0x3b, 0x10, 0x94, 0x0c, 0x67, 0x3f, 0x91, 0xc2, 0x29, 0xec, 0x94,
	0x21, 0x0d, 0x9f, 0x3f, 0x84, 0xad, 0xa3, 0x1c, 0x1d, 0x3e, 0xd2, 0xb5, 0x8f, 0x5e, 0x82, 0x67,
	0xe2, 0x14, 0xbe, 0x78, 0x20, 0x6c, 0x64, 0x37, 0x3a, 0x7a, 0xb4, 0x6f, 0xad, 0xa6, 0xb0, 0x53,
	0x86, 0xa1, 0x85, 0xe7, 0x97, 0x08, 0xb5, 0xf0, 0x34, 0x12, 0x74, 0x09, 0x9e, 0xd9, 0x4d, 0x0b,
	0x4f, 0x23, 0x08, 0x2d, 0x3c, 0x5b, 0x4b, 0xfd, 0x00, 0x9e, 0x99, 0x70, 0x8b, 0x55, 0x63, 0x37,
	0x2d, 0x56, 0xcd, 0xd5, 0xc4, 0x83, 0xf5, 0xfd, 0x7e, 0x1f, 0xa0, 0x0e, 0x41, 0xe4, 0xad, 0xef,
	0xf7, 0xdd, 0xae, 0x73, 0x3e, 0x78, 0x1f, 0x94, 0x77, 0xeb, 0xab, 0x73, 0x6f, 0xf3, 0x47, 0x39,
	0xfd, 0x11, 0x00, 0x00, 0xff, 0xff, 0xff, 0xcd, 0x3d, 0x07, 0xd6, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LdapAggregatorClient is the client API for LdapAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LdapAggregatorClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type ldapAggregatorClient struct {
	cc *grpc.ClientConn
}

func NewLdapAggregatorClient(cc *grpc.ClientConn) LdapAggregatorClient {
	return &ldapAggregatorClient{cc}
}

func (c *ldapAggregatorClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/ldap_aggregator.LdapAggregator/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ldapAggregatorClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/ldap_aggregator.LdapAggregator/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ldapAggregatorClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/ldap_aggregator.LdapAggregator/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ldapAggregatorClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/ldap_aggregator.LdapAggregator/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ldapAggregatorClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/ldap_aggregator.LdapAggregator/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LdapAggregatorServer is the server API for LdapAggregator service.
type LdapAggregatorServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedLdapAggregatorServer can be embedded to have forward compatible implementations.
type UnimplementedLdapAggregatorServer struct {
}

func (*UnimplementedLdapAggregatorServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedLdapAggregatorServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedLdapAggregatorServer) Read(ctx context.Context, req *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedLdapAggregatorServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedLdapAggregatorServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterLdapAggregatorServer(s *grpc.Server, srv LdapAggregatorServer) {
	s.RegisterService(&_LdapAggregator_serviceDesc, srv)
}

func _LdapAggregator_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LdapAggregatorServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldap_aggregator.LdapAggregator/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LdapAggregatorServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LdapAggregator_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LdapAggregatorServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldap_aggregator.LdapAggregator/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LdapAggregatorServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LdapAggregator_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LdapAggregatorServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldap_aggregator.LdapAggregator/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LdapAggregatorServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LdapAggregator_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LdapAggregatorServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldap_aggregator.LdapAggregator/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LdapAggregatorServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LdapAggregator_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LdapAggregatorServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldap_aggregator.LdapAggregator/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LdapAggregatorServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LdapAggregator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ldap_aggregator.LdapAggregator",
	HandlerType: (*LdapAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LdapAggregator_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LdapAggregator_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _LdapAggregator_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _LdapAggregator_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LdapAggregator_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
